### ISSUE TITLE
Label page A large number of duplicate labels  | Have been solved

### ISSUE THREAD

**Issue by bubbl000** [gndx/ev0-astro-theme#34]
Hello, I found the blog framework you wrote is very nice, so I used it to learn and change it to my favorite style, and then I found a situation that there would be a lot of repeats in the tag page, and then I asked the ai , ai gave a solution. Now replacing the function with this will solve the duplication problem

I don't know how to apply submit code without using github I am not a professional programmer and only know a little html and css so here is the question

Here is the modified code       src\utils\getAllTags.ts
--------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------
export const getTaxonomy = async (collection: string, name: string) => {
  const singlePages = await getCollection(collection);
  const taxonomyPages = singlePages.map((page) => page.data[name]);
  let taxonomies = [];
  for (let i = 0; i < taxonomyPages.length; i++) {
    const categoryArray = taxonomyPages[i];
    for (let j = 0; j < categoryArray.length; j++) {
      const newTaxonomy = {
        name: categoryArray[j],
        slug: slugify(categoryArray[j]),
      };
      if (!taxonomies.find(taxonomy => taxonomy.name === newTaxonomy.name && taxonomy.slug === newTaxonomy.slug)) {
        taxonomies.push(newTaxonomy);
      }
    }
  }
  return taxonomies;
};

![image](https://github.com/gndx/ev0-astro-theme/assets/108770692/fa08a445-0cef-444b-9e2d-91a2071da0bd)

**Comment by gndx** [comment]
Please add your Code in PR 👍
